name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-x64:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Restore
        run: msbuild VelocityGrid/VelocityGrid.slnx /t:Restore /m /p:Configuration=Debug /p:Platform=x64
      - name: Build
        run: msbuild VelocityGrid/VelocityGrid.slnx /t:Build /m /p:Configuration=Debug /p:Platform=x64
